import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AxiosInterceptor } from '@/services/AxiosInterceptor';
import { ReduxProviders } from '@/provider/ReduxProvider';
import ReactQueryProvider from '@/provider/ReactQueryProvider';
import {PrimeReactProvider} from "primereact/api";

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr">
      <ReduxProviders>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ReactQueryProvider>
            <AxiosInterceptor>
              <PrimeReactProvider>

              {children}

              </PrimeReactProvider>
              </AxiosInterceptor>
          </ReactQueryProvider>
        </body>
      </ReduxProviders>
    </html>
  );
}
